name: securite_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  flutter_secure_storage: ^10.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  local_auth: ^3.0.0
  dart_jsonwebtoken: ^3.1.1   # downgraded to avoid pointycastle 4 conflict
  pointycastle: ^3.9.1
  http_certificate_pinning: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/certs/safeo.pem